name: Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,2,4,6,8,10,12,14,16,18,20,22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: x64
      - name: download
        run: |
          wget -N ${{ secrets.URL }}
          tar -zxvf ${{ secrets.NAME }}
      - name: Update
        env: 
          NAME: ${{ secrets.NAME }}
        run: |
          python update.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'auto update'
          add: './python'
